#!/usr/bin/env bash
# Writes the part of Asterisk's config that can't be committed (issue #14), into
# asterisk/config/pjsip_generated.conf, which pjsip.conf includes and git ignores:
#   - the SIP passwords for 1001 and 2000, generated once into .env and kept after that;
#   - the laptop's current Wi-Fi address, read again on every run because it changes
#     between networks (issue #27).
#
# Usage: asterisk/configure.sh            generate the file
#        asterisk/configure.sh accounts   print what to type into the softphones
set -euo pipefail
cd "$(dirname "$0")/.."

env_file=.env
out=asterisk/config/pjsip_generated.conf

# The value of KEY in .env, or nothing.
env_get() { sed -n "s/^$1=//p" "$env_file" | tail -n 1; }

# Sets KEY in .env, replacing its line if there is one.
env_set() {
  if grep -q "^$1=" "$env_file"; then
    sed -i "s/^$1=.*/$1=$2/" "$env_file"
  else
    printf '%s=%s\n' "$1" "$2" >> "$env_file"
  fi
}

# 24 characters from 31 that can't be mistaken for each other (no 0/o, no 1/l/i), in groups
# of four so they can be typed into a phone: 24 x log2(31), about 119 bits.
new_password() {
  local chars
  chars=$(head -c 4096 /dev/urandom | LC_ALL=C tr -dc 'abcdefghjkmnpqrstuvwxyz23456789')
  echo "${chars:0:24}" | sed 's/..../&-/g; s/-$//'
}

# The IPv4 address of the Windows interface that holds the default route: the Wi-Fi.
detect_lan_ip() {
  powershell.exe -NoProfile -NonInteractive -Command '
    $r = Get-NetRoute -DestinationPrefix "0.0.0.0/0" |
      Sort-Object { $_.RouteMetric + $_.InterfaceMetric } | Select-Object -First 1
    (Get-NetIPAddress -InterfaceIndex $r.ifIndex -AddressFamily IPv4).IPAddress' | tr -d '\r'
}

if [ "${1:-}" = accounts ]; then
  [ -f "$out" ] || { echo "Run make asterisk-up first." >&2; exit 1; }
  server=$(sed -n 's/^external_signaling_address=//p' "$out")
  for ext in 1001 2000; do
    echo "$ext: username $ext, password $(env_get "SIP_${ext}_PASSWORD"), domain $server, transport UDP, port 5060"
  done
  exit 0
fi

[ -f "$env_file" ] || { cp .env.example "$env_file"; echo "Created $env_file from .env.example"; }

for ext in 1001 2000; do
  if [ -z "$(env_get "SIP_${ext}_PASSWORD")" ]; then
    env_set "SIP_${ext}_PASSWORD" "$(new_password)"
    echo "Generated SIP_${ext}_PASSWORD in $env_file"
  fi
done

lan_ip=$(env_get LAN_IP)
[ -n "$lan_ip" ] || lan_ip=$(detect_lan_ip)
# One private IPv4 address, or stop: this project runs on the local Wi-Fi only.
if ! [[ $lan_ip =~ ^(10|192\.168|172\.(1[6-9]|2[0-9]|3[01]))(\.[0-9]{1,3}){2,3}$ ]]; then
  echo "Expected one private IPv4 address for the Wi-Fi, got '$lan_ip'. Set LAN_IP in $env_file." >&2
  exit 1
fi

cat > "$out" <<EOF
; Generated by asterisk/configure.sh from .env. Don't edit it, and never commit it: it holds
; the SIP passwords. Included by pjsip.conf.

; The laptop's Wi-Fi address, which the phones dial.
[transport-udp](+)
external_signaling_address=$lan_ip
external_media_address=$lan_ip

; The same address in the From header of calls to a phone, so the phone can redial the caller.
[wifi-address](!)
from_domain=$lan_ip

[1001-auth]
type=auth
auth_type=digest
username=1001
password=$(env_get SIP_1001_PASSWORD)

[2000-auth]
type=auth
auth_type=digest
username=2000
password=$(env_get SIP_2000_PASSWORD)
EOF
echo "Wrote $out: Asterisk will advertise $lan_ip"
